/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleRegisterRouteImport } from './routes/$locale.register'
import { Route as LocaleOnboardingRouteImport } from './routes/$locale.onboarding'
import { Route as LocaleLoginRouteImport } from './routes/$locale.login'
import { Route as LocaleOOrganizationSlugAdminRouteImport } from './routes/$locale.o.$organizationSlug._admin'
import { Route as LocaleOOrganizationSlugAdminSettingsRouteImport } from './routes/$locale.o.$organizationSlug._admin._settings'
import { Route as LocaleOOrganizationSlugAdminSalesRouteImport } from './routes/$locale.o.$organizationSlug._admin._sales'
import { Route as LocaleOOrganizationSlugAdminOperationsRouteImport } from './routes/$locale.o.$organizationSlug._admin._operations'
import { Route as LocaleOOrganizationSlugAdminMarketingRouteImport } from './routes/$locale.o.$organizationSlug._admin._marketing'
import { Route as LocaleOOrganizationSlugAdminGeneralRouteImport } from './routes/$locale.o.$organizationSlug._admin._general'
import { Route as LocaleOOrganizationSlugAdminGeneralIndexRouteImport } from './routes/$locale.o.$organizationSlug._admin._general.index'
import { Route as LocaleOOrganizationSlugAdminSettingsAccountRouteImport } from './routes/$locale.o.$organizationSlug._admin._settings.account'
import { Route as LocaleOOrganizationSlugAdminSalesLeadsRouteImport } from './routes/$locale.o.$organizationSlug._admin._sales.leads'
import { Route as LocaleOOrganizationSlugAdminSalesCustomerOrdersRouteImport } from './routes/$locale.o.$organizationSlug._admin._sales.customer-orders'
import { Route as LocaleOOrganizationSlugAdminOperationsSuppliersRouteImport } from './routes/$locale.o.$organizationSlug._admin._operations.suppliers'
import { Route as LocaleOOrganizationSlugAdminOperationsSupplierOrdersRouteImport } from './routes/$locale.o.$organizationSlug._admin._operations.supplier-orders'
import { Route as LocaleOOrganizationSlugAdminOperationsQuotesRouteImport } from './routes/$locale.o.$organizationSlug._admin._operations.quotes'
import { Route as LocaleOOrganizationSlugAdminOperationsProductsRouteImport } from './routes/$locale.o.$organizationSlug._admin._operations.products'
import { Route as LocaleOOrganizationSlugAdminOperationsInventoryRouteImport } from './routes/$locale.o.$organizationSlug._admin._operations.inventory'
import { Route as LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRouteImport } from './routes/$locale.o.$organizationSlug._admin._operations.supplier-orders_.$orderId'
import { Route as LocaleOOrganizationSlugAdminMarketingMarketingCalendarRouteImport } from './routes/$locale.o.$organizationSlug._admin._marketing.marketing.calendar'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRegisterRoute = LocaleRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOnboardingRoute = LocaleOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOOrganizationSlugAdminRoute =
  LocaleOOrganizationSlugAdminRouteImport.update({
    id: '/o/$organizationSlug/_admin',
    path: '/o/$organizationSlug',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleOOrganizationSlugAdminSettingsRoute =
  LocaleOOrganizationSlugAdminSettingsRouteImport.update({
    id: '/_settings',
    getParentRoute: () => LocaleOOrganizationSlugAdminRoute,
  } as any)
const LocaleOOrganizationSlugAdminSalesRoute =
  LocaleOOrganizationSlugAdminSalesRouteImport.update({
    id: '/_sales',
    getParentRoute: () => LocaleOOrganizationSlugAdminRoute,
  } as any)
const LocaleOOrganizationSlugAdminOperationsRoute =
  LocaleOOrganizationSlugAdminOperationsRouteImport.update({
    id: '/_operations',
    getParentRoute: () => LocaleOOrganizationSlugAdminRoute,
  } as any)
const LocaleOOrganizationSlugAdminMarketingRoute =
  LocaleOOrganizationSlugAdminMarketingRouteImport.update({
    id: '/_marketing',
    getParentRoute: () => LocaleOOrganizationSlugAdminRoute,
  } as any)
const LocaleOOrganizationSlugAdminGeneralRoute =
  LocaleOOrganizationSlugAdminGeneralRouteImport.update({
    id: '/_general',
    getParentRoute: () => LocaleOOrganizationSlugAdminRoute,
  } as any)
const LocaleOOrganizationSlugAdminGeneralIndexRoute =
  LocaleOOrganizationSlugAdminGeneralIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleOOrganizationSlugAdminGeneralRoute,
  } as any)
const LocaleOOrganizationSlugAdminSettingsAccountRoute =
  LocaleOOrganizationSlugAdminSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LocaleOOrganizationSlugAdminSettingsRoute,
  } as any)
const LocaleOOrganizationSlugAdminSalesLeadsRoute =
  LocaleOOrganizationSlugAdminSalesLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => LocaleOOrganizationSlugAdminSalesRoute,
  } as any)
const LocaleOOrganizationSlugAdminSalesCustomerOrdersRoute =
  LocaleOOrganizationSlugAdminSalesCustomerOrdersRouteImport.update({
    id: '/customer-orders',
    path: '/customer-orders',
    getParentRoute: () => LocaleOOrganizationSlugAdminSalesRoute,
  } as any)
const LocaleOOrganizationSlugAdminOperationsSuppliersRoute =
  LocaleOOrganizationSlugAdminOperationsSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => LocaleOOrganizationSlugAdminOperationsRoute,
  } as any)
const LocaleOOrganizationSlugAdminOperationsSupplierOrdersRoute =
  LocaleOOrganizationSlugAdminOperationsSupplierOrdersRouteImport.update({
    id: '/supplier-orders',
    path: '/supplier-orders',
    getParentRoute: () => LocaleOOrganizationSlugAdminOperationsRoute,
  } as any)
const LocaleOOrganizationSlugAdminOperationsQuotesRoute =
  LocaleOOrganizationSlugAdminOperationsQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => LocaleOOrganizationSlugAdminOperationsRoute,
  } as any)
const LocaleOOrganizationSlugAdminOperationsProductsRoute =
  LocaleOOrganizationSlugAdminOperationsProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => LocaleOOrganizationSlugAdminOperationsRoute,
  } as any)
const LocaleOOrganizationSlugAdminOperationsInventoryRoute =
  LocaleOOrganizationSlugAdminOperationsInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => LocaleOOrganizationSlugAdminOperationsRoute,
  } as any)
const LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRoute =
  LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRouteImport.update(
    {
      id: '/supplier-orders_/$orderId',
      path: '/supplier-orders/$orderId',
      getParentRoute: () => LocaleOOrganizationSlugAdminOperationsRoute,
    } as any,
  )
const LocaleOOrganizationSlugAdminMarketingMarketingCalendarRoute =
  LocaleOOrganizationSlugAdminMarketingMarketingCalendarRouteImport.update({
    id: '/marketing/calendar',
    path: '/marketing/calendar',
    getParentRoute: () => LocaleOOrganizationSlugAdminMarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/onboarding': typeof LocaleOnboardingRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/o/$organizationSlug': typeof LocaleOOrganizationSlugAdminSettingsRouteWithChildren
  '/$locale/o/$organizationSlug/inventory': typeof LocaleOOrganizationSlugAdminOperationsInventoryRoute
  '/$locale/o/$organizationSlug/products': typeof LocaleOOrganizationSlugAdminOperationsProductsRoute
  '/$locale/o/$organizationSlug/quotes': typeof LocaleOOrganizationSlugAdminOperationsQuotesRoute
  '/$locale/o/$organizationSlug/supplier-orders': typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersRoute
  '/$locale/o/$organizationSlug/suppliers': typeof LocaleOOrganizationSlugAdminOperationsSuppliersRoute
  '/$locale/o/$organizationSlug/customer-orders': typeof LocaleOOrganizationSlugAdminSalesCustomerOrdersRoute
  '/$locale/o/$organizationSlug/leads': typeof LocaleOOrganizationSlugAdminSalesLeadsRoute
  '/$locale/o/$organizationSlug/account': typeof LocaleOOrganizationSlugAdminSettingsAccountRoute
  '/$locale/o/$organizationSlug/': typeof LocaleOOrganizationSlugAdminGeneralIndexRoute
  '/$locale/o/$organizationSlug/marketing/calendar': typeof LocaleOOrganizationSlugAdminMarketingMarketingCalendarRoute
  '/$locale/o/$organizationSlug/supplier-orders/$orderId': typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/onboarding': typeof LocaleOnboardingRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/o/$organizationSlug': typeof LocaleOOrganizationSlugAdminGeneralIndexRoute
  '/$locale/o/$organizationSlug/inventory': typeof LocaleOOrganizationSlugAdminOperationsInventoryRoute
  '/$locale/o/$organizationSlug/products': typeof LocaleOOrganizationSlugAdminOperationsProductsRoute
  '/$locale/o/$organizationSlug/quotes': typeof LocaleOOrganizationSlugAdminOperationsQuotesRoute
  '/$locale/o/$organizationSlug/supplier-orders': typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersRoute
  '/$locale/o/$organizationSlug/suppliers': typeof LocaleOOrganizationSlugAdminOperationsSuppliersRoute
  '/$locale/o/$organizationSlug/customer-orders': typeof LocaleOOrganizationSlugAdminSalesCustomerOrdersRoute
  '/$locale/o/$organizationSlug/leads': typeof LocaleOOrganizationSlugAdminSalesLeadsRoute
  '/$locale/o/$organizationSlug/account': typeof LocaleOOrganizationSlugAdminSettingsAccountRoute
  '/$locale/o/$organizationSlug/marketing/calendar': typeof LocaleOOrganizationSlugAdminMarketingMarketingCalendarRoute
  '/$locale/o/$organizationSlug/supplier-orders/$orderId': typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/onboarding': typeof LocaleOnboardingRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/o/$organizationSlug/_admin': typeof LocaleOOrganizationSlugAdminRouteWithChildren
  '/$locale/o/$organizationSlug/_admin/_general': typeof LocaleOOrganizationSlugAdminGeneralRouteWithChildren
  '/$locale/o/$organizationSlug/_admin/_marketing': typeof LocaleOOrganizationSlugAdminMarketingRouteWithChildren
  '/$locale/o/$organizationSlug/_admin/_operations': typeof LocaleOOrganizationSlugAdminOperationsRouteWithChildren
  '/$locale/o/$organizationSlug/_admin/_sales': typeof LocaleOOrganizationSlugAdminSalesRouteWithChildren
  '/$locale/o/$organizationSlug/_admin/_settings': typeof LocaleOOrganizationSlugAdminSettingsRouteWithChildren
  '/$locale/o/$organizationSlug/_admin/_operations/inventory': typeof LocaleOOrganizationSlugAdminOperationsInventoryRoute
  '/$locale/o/$organizationSlug/_admin/_operations/products': typeof LocaleOOrganizationSlugAdminOperationsProductsRoute
  '/$locale/o/$organizationSlug/_admin/_operations/quotes': typeof LocaleOOrganizationSlugAdminOperationsQuotesRoute
  '/$locale/o/$organizationSlug/_admin/_operations/supplier-orders': typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersRoute
  '/$locale/o/$organizationSlug/_admin/_operations/suppliers': typeof LocaleOOrganizationSlugAdminOperationsSuppliersRoute
  '/$locale/o/$organizationSlug/_admin/_sales/customer-orders': typeof LocaleOOrganizationSlugAdminSalesCustomerOrdersRoute
  '/$locale/o/$organizationSlug/_admin/_sales/leads': typeof LocaleOOrganizationSlugAdminSalesLeadsRoute
  '/$locale/o/$organizationSlug/_admin/_settings/account': typeof LocaleOOrganizationSlugAdminSettingsAccountRoute
  '/$locale/o/$organizationSlug/_admin/_general/': typeof LocaleOOrganizationSlugAdminGeneralIndexRoute
  '/$locale/o/$organizationSlug/_admin/_marketing/marketing/calendar': typeof LocaleOOrganizationSlugAdminMarketingMarketingCalendarRoute
  '/$locale/o/$organizationSlug/_admin/_operations/supplier-orders_/$orderId': typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/onboarding'
    | '/$locale/register'
    | '/$locale/'
    | '/$locale/o/$organizationSlug'
    | '/$locale/o/$organizationSlug/inventory'
    | '/$locale/o/$organizationSlug/products'
    | '/$locale/o/$organizationSlug/quotes'
    | '/$locale/o/$organizationSlug/supplier-orders'
    | '/$locale/o/$organizationSlug/suppliers'
    | '/$locale/o/$organizationSlug/customer-orders'
    | '/$locale/o/$organizationSlug/leads'
    | '/$locale/o/$organizationSlug/account'
    | '/$locale/o/$organizationSlug/'
    | '/$locale/o/$organizationSlug/marketing/calendar'
    | '/$locale/o/$organizationSlug/supplier-orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/login'
    | '/$locale/onboarding'
    | '/$locale/register'
    | '/$locale'
    | '/$locale/o/$organizationSlug'
    | '/$locale/o/$organizationSlug/inventory'
    | '/$locale/o/$organizationSlug/products'
    | '/$locale/o/$organizationSlug/quotes'
    | '/$locale/o/$organizationSlug/supplier-orders'
    | '/$locale/o/$organizationSlug/suppliers'
    | '/$locale/o/$organizationSlug/customer-orders'
    | '/$locale/o/$organizationSlug/leads'
    | '/$locale/o/$organizationSlug/account'
    | '/$locale/o/$organizationSlug/marketing/calendar'
    | '/$locale/o/$organizationSlug/supplier-orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/onboarding'
    | '/$locale/register'
    | '/$locale/'
    | '/$locale/o/$organizationSlug/_admin'
    | '/$locale/o/$organizationSlug/_admin/_general'
    | '/$locale/o/$organizationSlug/_admin/_marketing'
    | '/$locale/o/$organizationSlug/_admin/_operations'
    | '/$locale/o/$organizationSlug/_admin/_sales'
    | '/$locale/o/$organizationSlug/_admin/_settings'
    | '/$locale/o/$organizationSlug/_admin/_operations/inventory'
    | '/$locale/o/$organizationSlug/_admin/_operations/products'
    | '/$locale/o/$organizationSlug/_admin/_operations/quotes'
    | '/$locale/o/$organizationSlug/_admin/_operations/supplier-orders'
    | '/$locale/o/$organizationSlug/_admin/_operations/suppliers'
    | '/$locale/o/$organizationSlug/_admin/_sales/customer-orders'
    | '/$locale/o/$organizationSlug/_admin/_sales/leads'
    | '/$locale/o/$organizationSlug/_admin/_settings/account'
    | '/$locale/o/$organizationSlug/_admin/_general/'
    | '/$locale/o/$organizationSlug/_admin/_marketing/marketing/calendar'
    | '/$locale/o/$organizationSlug/_admin/_operations/supplier-orders_/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/register': {
      id: '/$locale/register'
      path: '/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleRegisterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/onboarding': {
      id: '/$locale/onboarding'
      path: '/onboarding'
      fullPath: '/$locale/onboarding'
      preLoaderRoute: typeof LocaleOnboardingRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/o/$organizationSlug/_admin': {
      id: '/$locale/o/$organizationSlug/_admin'
      path: '/o/$organizationSlug'
      fullPath: '/$locale/o/$organizationSlug'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/o/$organizationSlug/_admin/_settings': {
      id: '/$locale/o/$organizationSlug/_admin/_settings'
      path: ''
      fullPath: '/$locale/o/$organizationSlug'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminSettingsRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminRoute
    }
    '/$locale/o/$organizationSlug/_admin/_sales': {
      id: '/$locale/o/$organizationSlug/_admin/_sales'
      path: ''
      fullPath: '/$locale/o/$organizationSlug'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminSalesRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminRoute
    }
    '/$locale/o/$organizationSlug/_admin/_operations': {
      id: '/$locale/o/$organizationSlug/_admin/_operations'
      path: ''
      fullPath: '/$locale/o/$organizationSlug'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminOperationsRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminRoute
    }
    '/$locale/o/$organizationSlug/_admin/_marketing': {
      id: '/$locale/o/$organizationSlug/_admin/_marketing'
      path: ''
      fullPath: '/$locale/o/$organizationSlug'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminMarketingRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminRoute
    }
    '/$locale/o/$organizationSlug/_admin/_general': {
      id: '/$locale/o/$organizationSlug/_admin/_general'
      path: ''
      fullPath: '/$locale/o/$organizationSlug'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminGeneralRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminRoute
    }
    '/$locale/o/$organizationSlug/_admin/_general/': {
      id: '/$locale/o/$organizationSlug/_admin/_general/'
      path: '/'
      fullPath: '/$locale/o/$organizationSlug/'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminGeneralIndexRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminGeneralRoute
    }
    '/$locale/o/$organizationSlug/_admin/_settings/account': {
      id: '/$locale/o/$organizationSlug/_admin/_settings/account'
      path: '/account'
      fullPath: '/$locale/o/$organizationSlug/account'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminSettingsAccountRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminSettingsRoute
    }
    '/$locale/o/$organizationSlug/_admin/_sales/leads': {
      id: '/$locale/o/$organizationSlug/_admin/_sales/leads'
      path: '/leads'
      fullPath: '/$locale/o/$organizationSlug/leads'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminSalesLeadsRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminSalesRoute
    }
    '/$locale/o/$organizationSlug/_admin/_sales/customer-orders': {
      id: '/$locale/o/$organizationSlug/_admin/_sales/customer-orders'
      path: '/customer-orders'
      fullPath: '/$locale/o/$organizationSlug/customer-orders'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminSalesCustomerOrdersRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminSalesRoute
    }
    '/$locale/o/$organizationSlug/_admin/_operations/suppliers': {
      id: '/$locale/o/$organizationSlug/_admin/_operations/suppliers'
      path: '/suppliers'
      fullPath: '/$locale/o/$organizationSlug/suppliers'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminOperationsSuppliersRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminOperationsRoute
    }
    '/$locale/o/$organizationSlug/_admin/_operations/supplier-orders': {
      id: '/$locale/o/$organizationSlug/_admin/_operations/supplier-orders'
      path: '/supplier-orders'
      fullPath: '/$locale/o/$organizationSlug/supplier-orders'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminOperationsRoute
    }
    '/$locale/o/$organizationSlug/_admin/_operations/quotes': {
      id: '/$locale/o/$organizationSlug/_admin/_operations/quotes'
      path: '/quotes'
      fullPath: '/$locale/o/$organizationSlug/quotes'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminOperationsQuotesRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminOperationsRoute
    }
    '/$locale/o/$organizationSlug/_admin/_operations/products': {
      id: '/$locale/o/$organizationSlug/_admin/_operations/products'
      path: '/products'
      fullPath: '/$locale/o/$organizationSlug/products'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminOperationsProductsRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminOperationsRoute
    }
    '/$locale/o/$organizationSlug/_admin/_operations/inventory': {
      id: '/$locale/o/$organizationSlug/_admin/_operations/inventory'
      path: '/inventory'
      fullPath: '/$locale/o/$organizationSlug/inventory'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminOperationsInventoryRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminOperationsRoute
    }
    '/$locale/o/$organizationSlug/_admin/_operations/supplier-orders_/$orderId': {
      id: '/$locale/o/$organizationSlug/_admin/_operations/supplier-orders_/$orderId'
      path: '/supplier-orders/$orderId'
      fullPath: '/$locale/o/$organizationSlug/supplier-orders/$orderId'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminOperationsRoute
    }
    '/$locale/o/$organizationSlug/_admin/_marketing/marketing/calendar': {
      id: '/$locale/o/$organizationSlug/_admin/_marketing/marketing/calendar'
      path: '/marketing/calendar'
      fullPath: '/$locale/o/$organizationSlug/marketing/calendar'
      preLoaderRoute: typeof LocaleOOrganizationSlugAdminMarketingMarketingCalendarRouteImport
      parentRoute: typeof LocaleOOrganizationSlugAdminMarketingRoute
    }
  }
}

interface LocaleOOrganizationSlugAdminGeneralRouteChildren {
  LocaleOOrganizationSlugAdminGeneralIndexRoute: typeof LocaleOOrganizationSlugAdminGeneralIndexRoute
}

const LocaleOOrganizationSlugAdminGeneralRouteChildren: LocaleOOrganizationSlugAdminGeneralRouteChildren =
  {
    LocaleOOrganizationSlugAdminGeneralIndexRoute:
      LocaleOOrganizationSlugAdminGeneralIndexRoute,
  }

const LocaleOOrganizationSlugAdminGeneralRouteWithChildren =
  LocaleOOrganizationSlugAdminGeneralRoute._addFileChildren(
    LocaleOOrganizationSlugAdminGeneralRouteChildren,
  )

interface LocaleOOrganizationSlugAdminMarketingRouteChildren {
  LocaleOOrganizationSlugAdminMarketingMarketingCalendarRoute: typeof LocaleOOrganizationSlugAdminMarketingMarketingCalendarRoute
}

const LocaleOOrganizationSlugAdminMarketingRouteChildren: LocaleOOrganizationSlugAdminMarketingRouteChildren =
  {
    LocaleOOrganizationSlugAdminMarketingMarketingCalendarRoute:
      LocaleOOrganizationSlugAdminMarketingMarketingCalendarRoute,
  }

const LocaleOOrganizationSlugAdminMarketingRouteWithChildren =
  LocaleOOrganizationSlugAdminMarketingRoute._addFileChildren(
    LocaleOOrganizationSlugAdminMarketingRouteChildren,
  )

interface LocaleOOrganizationSlugAdminOperationsRouteChildren {
  LocaleOOrganizationSlugAdminOperationsInventoryRoute: typeof LocaleOOrganizationSlugAdminOperationsInventoryRoute
  LocaleOOrganizationSlugAdminOperationsProductsRoute: typeof LocaleOOrganizationSlugAdminOperationsProductsRoute
  LocaleOOrganizationSlugAdminOperationsQuotesRoute: typeof LocaleOOrganizationSlugAdminOperationsQuotesRoute
  LocaleOOrganizationSlugAdminOperationsSupplierOrdersRoute: typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersRoute
  LocaleOOrganizationSlugAdminOperationsSuppliersRoute: typeof LocaleOOrganizationSlugAdminOperationsSuppliersRoute
  LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRoute: typeof LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRoute
}

const LocaleOOrganizationSlugAdminOperationsRouteChildren: LocaleOOrganizationSlugAdminOperationsRouteChildren =
  {
    LocaleOOrganizationSlugAdminOperationsInventoryRoute:
      LocaleOOrganizationSlugAdminOperationsInventoryRoute,
    LocaleOOrganizationSlugAdminOperationsProductsRoute:
      LocaleOOrganizationSlugAdminOperationsProductsRoute,
    LocaleOOrganizationSlugAdminOperationsQuotesRoute:
      LocaleOOrganizationSlugAdminOperationsQuotesRoute,
    LocaleOOrganizationSlugAdminOperationsSupplierOrdersRoute:
      LocaleOOrganizationSlugAdminOperationsSupplierOrdersRoute,
    LocaleOOrganizationSlugAdminOperationsSuppliersRoute:
      LocaleOOrganizationSlugAdminOperationsSuppliersRoute,
    LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRoute:
      LocaleOOrganizationSlugAdminOperationsSupplierOrdersOrderIdRoute,
  }

const LocaleOOrganizationSlugAdminOperationsRouteWithChildren =
  LocaleOOrganizationSlugAdminOperationsRoute._addFileChildren(
    LocaleOOrganizationSlugAdminOperationsRouteChildren,
  )

interface LocaleOOrganizationSlugAdminSalesRouteChildren {
  LocaleOOrganizationSlugAdminSalesCustomerOrdersRoute: typeof LocaleOOrganizationSlugAdminSalesCustomerOrdersRoute
  LocaleOOrganizationSlugAdminSalesLeadsRoute: typeof LocaleOOrganizationSlugAdminSalesLeadsRoute
}

const LocaleOOrganizationSlugAdminSalesRouteChildren: LocaleOOrganizationSlugAdminSalesRouteChildren =
  {
    LocaleOOrganizationSlugAdminSalesCustomerOrdersRoute:
      LocaleOOrganizationSlugAdminSalesCustomerOrdersRoute,
    LocaleOOrganizationSlugAdminSalesLeadsRoute:
      LocaleOOrganizationSlugAdminSalesLeadsRoute,
  }

const LocaleOOrganizationSlugAdminSalesRouteWithChildren =
  LocaleOOrganizationSlugAdminSalesRoute._addFileChildren(
    LocaleOOrganizationSlugAdminSalesRouteChildren,
  )

interface LocaleOOrganizationSlugAdminSettingsRouteChildren {
  LocaleOOrganizationSlugAdminSettingsAccountRoute: typeof LocaleOOrganizationSlugAdminSettingsAccountRoute
}

const LocaleOOrganizationSlugAdminSettingsRouteChildren: LocaleOOrganizationSlugAdminSettingsRouteChildren =
  {
    LocaleOOrganizationSlugAdminSettingsAccountRoute:
      LocaleOOrganizationSlugAdminSettingsAccountRoute,
  }

const LocaleOOrganizationSlugAdminSettingsRouteWithChildren =
  LocaleOOrganizationSlugAdminSettingsRoute._addFileChildren(
    LocaleOOrganizationSlugAdminSettingsRouteChildren,
  )

interface LocaleOOrganizationSlugAdminRouteChildren {
  LocaleOOrganizationSlugAdminGeneralRoute: typeof LocaleOOrganizationSlugAdminGeneralRouteWithChildren
  LocaleOOrganizationSlugAdminMarketingRoute: typeof LocaleOOrganizationSlugAdminMarketingRouteWithChildren
  LocaleOOrganizationSlugAdminOperationsRoute: typeof LocaleOOrganizationSlugAdminOperationsRouteWithChildren
  LocaleOOrganizationSlugAdminSalesRoute: typeof LocaleOOrganizationSlugAdminSalesRouteWithChildren
  LocaleOOrganizationSlugAdminSettingsRoute: typeof LocaleOOrganizationSlugAdminSettingsRouteWithChildren
}

const LocaleOOrganizationSlugAdminRouteChildren: LocaleOOrganizationSlugAdminRouteChildren =
  {
    LocaleOOrganizationSlugAdminGeneralRoute:
      LocaleOOrganizationSlugAdminGeneralRouteWithChildren,
    LocaleOOrganizationSlugAdminMarketingRoute:
      LocaleOOrganizationSlugAdminMarketingRouteWithChildren,
    LocaleOOrganizationSlugAdminOperationsRoute:
      LocaleOOrganizationSlugAdminOperationsRouteWithChildren,
    LocaleOOrganizationSlugAdminSalesRoute:
      LocaleOOrganizationSlugAdminSalesRouteWithChildren,
    LocaleOOrganizationSlugAdminSettingsRoute:
      LocaleOOrganizationSlugAdminSettingsRouteWithChildren,
  }

const LocaleOOrganizationSlugAdminRouteWithChildren =
  LocaleOOrganizationSlugAdminRoute._addFileChildren(
    LocaleOOrganizationSlugAdminRouteChildren,
  )

interface LocaleRouteChildren {
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleOnboardingRoute: typeof LocaleOnboardingRoute
  LocaleRegisterRoute: typeof LocaleRegisterRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleOOrganizationSlugAdminRoute: typeof LocaleOOrganizationSlugAdminRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleOnboardingRoute: LocaleOnboardingRoute,
  LocaleRegisterRoute: LocaleRegisterRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleOOrganizationSlugAdminRoute:
    LocaleOOrganizationSlugAdminRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
